version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn run dev
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
  api:
    command: yarn run dev
    volumes:
      - ./api/src:/usr/src/app/src
  auth:
    command: yarn run dev
    volumes:
      - ./auth/src:/usr/src/app/src
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
